### ISSUE TITLE
Determine candidate patch

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/careen#11]
New:
- what is the process for adding a patch to our docker build
---

Old:
Find a docker patch that we should use for two reasons:

a. increases the stability of the version of Docker we are going to ship with
b. exercise careen in jenkins

**Comment by davidewatson** [comment]
We are currently using the patches RedHat applies as the candidate set. Someone needs to go through the list of patches and determine which we want to carry forward. IMHO, stability and security patches should almost always be carried forward.

To obtain the code which RedHat is using you should be able do the following (note that these instructions are currently incomplete as they do not describe how to get the patches):

```
docker run --rm -it fedora:24 bash
dnf install -y cpio tar git
mkdir -p /tmp/docker && cd /tmp/docker
curl https://yum.dockerproject.org/repo/main/centos/7/Packages/docker-engine-1.11.2-1.el7.centos.src.rpm >  docker-engine-1.11.2-1.el7.centos.src.rpm
tar xfz docker-engine.tar.gz 
```

**Comment by coffeepac** [comment]
modifying this to cover what the future process for this will be is.

**Comment by leahnp** [comment]
Review instructions?

**Comment by coffeepac** [comment]
waiting for input from @countspongebob or we close this in one week (this comment is timestamped, use that for now)

**Comment by coffeepac** [comment]
waiting for doc from @davidewatson about where to find vulnerabilities and other Items of Interest.

**Comment by davidewatson** [comment]
https://hanjin.atlassian.net/wiki/display/AG/Careen+Maintenance+for+Docker
