### ISSUE TITLE
create CoreOS image with samsung docker installed

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/careen#17]
in the spirit of leaving CoreOS unmodified after it hits a node we should be creating our own CoreOS image with docker pre-installed

**Comment by davidewatson** [comment]
Note that I am currently installing docker in the same way that the cni pluggins are installed, so if we decide to do this, then it might make sense to bake those in as well. One advantage of doing so is that node start time will be reduced, though probably not by much. A more significant advantage is that for some deployments an air-gapped solution is necessary for high availability, regulatory reasons, etc. We will need to consider the on going maintenance cost required to maintain self hosted system images, as well as the benefits and drawbacks of various artifact management systems. The latter of these may be customer specific.

**Comment by venezia** [comment]
FWIW, CNI plugins will be delivered through a k8s manifest, not through a systemd unit moving forward.  https://github.com/projectcalico/canal/issues/32 hints to that.

**Comment by coffeepac** [comment]
this is too much work.  not needed.
